name: Build and Release Minecraft Mod

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/libs/*.jar

    - name: Bump version and create tag
      id: tag_version
      run: |
        # Ensure the version file exists
        VERSION_FILE="version.txt"
        if [ ! -f $VERSION_FILE ]; then echo "0.0.0" > $VERSION_FILE; fi
        
        # Read and increment the version number
        VERSION=$(cat $VERSION_FILE)
        IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
        PATCH=${VERSION_PARTS[2]}
        
        # Loop to find the next available tag version
        while git rev-parse "v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH" >/dev/null 2>&1; do
          PATCH=$((PATCH+1))
        done
        
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
        
        # Ensure the new tag is in the correct format
        TAG_NAME="v$NEW_VERSION"
        echo "Generated tag: $TAG_NAME"
        
        # Update version file
        echo $NEW_VERSION > $VERSION_FILE
        
        # Commit the new version and tag it
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add $VERSION_FILE
        git commit -m "Bump version to $NEW_VERSION"
        git tag -a "$TAG_NAME" -m "Version $NEW_VERSION"

    - name: Push tag to the repository
      run: |
        git push origin "$TAG_NAME"

    - name: Publish to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/libs/*.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "$TAG_NAME"
        name: "Release $TAG_NAME"
        body: "Automated release for version $TAG_NAME"
