name: Build and Release Minecraft Mod

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/libs/*.jar

    - name: Bump version and create tag
      id: tag_version
      run: |
        # Bump the version number (simple example, increments a patch version)
        VERSION_FILE="version.txt"
        if [ ! -f $VERSION_FILE ]; then echo "0.0.0" > $VERSION_FILE; fi
        VERSION=$(cat $VERSION_FILE)
        IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
        PATCH=${VERSION_PARTS[2]}
        PATCH=$((PATCH+1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
        echo $NEW_VERSION > $VERSION_FILE

        # Commit and tag the new version
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add $VERSION_FILE
        git commit -m "Bump version to $NEW_VERSION"
        git tag "v$NEW_VERSION"

    - name: Push tag to the repository
      run: |
        git push origin "v$(cat version.txt)"

    - name: Publish to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/libs/*.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v$(cat version.txt)"
        name: "Release v$(cat version.txt)"
        body: "Automated release for version v$(cat version.txt)"

